### ISSUE TITLE
Pads' link is not shown in sub-groups side menu even if enabled

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#57] opened 2016-10-19 15:28 UTC

**Comment by michelesbw** [comment] 2016-10-28 10:46
Also reported to plugin's dev here https://github.com/nlybe/Elgg-Etherpad/issues/3

**Comment by juho-jaakkola** [comment] 2017-05-07 16:47
Closing this as a duplicate of: https://github.com/sbwtech/sbw/issues/64

**Closed** 2017-05-07 17:14 UTC
Labels: bug
